'''
Differential geometry of manifolds. 

This module provides the bulk (interior) differential-geometric machinery for
fields living on a curved manifold, expressed as UFL tensor
quantities in curvilinear coordinates. 

  - Metric and curvature: g, g_c (co-/contravariant metric), detg and its
    variants, b (second fundamental form / shape operator), H (mean curvature,
    and H_Nabla_omega in terms of the covariant derivative of omega).
  - Connection and derivatives: Gamma (Christoffel symbols), covariant
    derivatives of vectors (Nabla_v), one-forms (Nabla_f), and two-covariant
    tensors (Nabla_ff), and the Laplace-Beltrami operator on scalars
    (Nabla_LB).
  - Rate-of-deformation tensors d, d_c for surface flows (including the
    normal-velocity contribution).
  - Index raising/lowering and frame maps: f_to_v, v_to_f, normalize,
    from_tangent_to_3D_space, from_3D_to_tangent, from_3D_to_normal, and their
    combinations, mapping between the tangent bundle of the manifold and the
    embedding 3D space.
  - Circle-related normals (N3d_c_r, Nt_c_r, n_c_r) and small UFL helpers
    (ufl_norm, euclidean_projection, vector_times_scalar, shape).

Most functions take the geometry argument 'omega' (a one-form, e.g. the
gradient of the height field z) and an optional gauge function 'nu'. The
frame field e(omega, nu), curvature K, surface normal, and embedding X are
module-level globals set externally according to the chosen gauge. 

Depends on FEniCS, UFL, and numpy; index objects and the 2D permutation symbol are
defined at module level for tensor expressions.
'''


from fenics import *
import ufl as ufl
import numpy as np

# Global variables which will be set according to the gauge choice
e = None
K = None
normal = None
X = None

'''
compute the norm of an ufl vector
Input values:
- 'v': an ufl vector
Return values:
- the norm of v, sqrt(v[i]*v[i]), computed with ufl
'''


def ufl_norm(x):
    return (sqrt(ufl.dot(x, x)))


epsilon = ufl.PermutationSymbol(2)

# definition of scalar, vectorial and tensorial quantities
# latin indexes run on 2d curvilinear coordinates
i, j, k, l, alpha, beta = ufl.indices(6)


# second fundamental form: b(z)[i,j] = b_{ij}_{al-izzi2020shear}
def b(omega, nu=None):
    return as_tensor((normal(omega, nu))[k] * (e(omega, nu)[i, k]).dx(j), (i, j))


# two-covariant metric tensor: g_{ij}
def g(omega, nu=None):
    return as_tensor(e(omega, nu)[i, k] * e(omega, nu)[j, k], (i, j))


# two-contravariant metric tensor: g^{ij}
def g_c(omega, nu=None):
    return ufl.inv(g(omega, nu))


# determinant of the two-covariant metric tensor
def detg(omega, nu=None):
    return ufl.det(g(omega, nu))


# absolute value of the two-covariant metric tensor
def abs_detg(omega, nu=None):
    return np.abs(ufl.det(g(omega, nu)))


# square root of the determinant of the two-covariant metric tensor
def sqrt_detg(omega, nu=None):
    return sqrt(detg(omega, nu))


# square root of the absolute value of the two-covariant metric tensor
def sqrt_abs_detg(omega, nu=None):
    return sqrt(abs_detg(omega, nu))


# mean curvature, H = H_{al-izzi2020shear}
def H(omega, nu=None):
    return (0.5 * g_c(omega, nu)[i, j] * b(omega, nu)[j, i])


# same as H(omega, nu), but expressed in terms of the covariant derivative of omega
def H_Nabla_omega(omega, nu=None):
    return (1.0 / 2.0 * sqrt_detg(omega, nu) * g_c(omega, nu)[i, j] * Nabla_f(omega, omega, nu)[j, i])


# Christoffel symbols of the second kind related to g: Gamma(omega, nu)[i,j,k] = {\Gamma^i_{jk}}_{al-izzi2020shear}
def Gamma(omega, nu=None):
    return as_tensor(0.5 * g_c(omega, nu)[i, l] * ((g(omega, nu)[l, k]).dx(j) + (g(omega, nu)[j, l]).dx(k) - (g(omega, nu)[j, k]).dx(l)), (i, j, k))


# covariant derivative of vector v with respect to \partial/partial x and with respect to the Levi-Civita connection generated by g: Nabla_v(v, omega, nu)[i, j] = {\Nabla_j v^i}_{al-izzi2020shear}
def Nabla_v(u, omega, nu=None):
    return as_tensor((u[i]).dx(j) + u[k] * Gamma(omega, nu)[i, k, j], (i, j))


# covariant derivative of one-form f with respect to \partial/partial x and with respect to the Levi-Civita connection generated by g: Nabla_f(f, omega, nu)[i, j] = {\Nabla_j f_i}_{al-izzi2020shear}
def Nabla_f(f, omega, nu=None):
    return as_tensor((f[i]).dx(j) - f[k] * Gamma(omega, nu)[k, i, j], (i, j))


# covariant derivative of a two-coavariant tensor t: Nabla_ff(t, omega, nu)[i, j, k] = \Nabla_k t_{ij}
def Nabla_ff(t, omega, nu=None):
    return as_tensor((t[i, j]).dx(k) - t[l, j] * Gamma(omega, nu)[l, i, k] - t[i, l] * Gamma(omega, nu)[l, j, k], (i, j, k))


# lalplace-beltrami operator applied to a scalar function f : Nabla_LB(f, omega, nu) = \Nabla_{LB} f_notes
def Nabla_LB(f, omega, nu=None):
    return (- 1.0 / sqrt_detg(omega, nu) * ((sqrt_detg(omega, nu) * g_c(omega, nu)[i, j] * (f.dx(j))).dx(i)))


# 2-covariant rate-of_deformation tensor for zero normal velocity: d(u, z)[i, j] = {d_{ij}}_{alizzi2020shear for zero w}
def d(v, w, omega, nu=None):
    return as_tensor(0.5 * (g(omega, nu)[i, k] * Nabla_v(v, omega, nu)[k, j] + g(omega, nu)[j, k] * Nabla_v(v, omega, nu)[k, i]) - (b(omega, nu)[i, j]) * w, (i, j))


# 2-contravariant rate-of_deformation tensor: d_c(u, un, z)[i, j] = {d^{ij}}_{alizzi2020shear}
def d_c(v, w, omega, nu=None):
    return as_tensor(g_c(omega, nu)[i, k] * g_c(omega, nu)[j, l] * d(v, w, omega, nu)[k, l], (i, j))


# given a vector and a scalar, return the vector vector^i * scalar
def vector_times_scalar(vector, scalar):
    return as_tensor(scalar * vector[i], (i))

'''
return the euclidean projection of a vector on another
Input values: 
    - 'v': the vector to be projected (d-dimensional)
    - 'n': the vector on which the projection will be made (d-dimensional)
Return values: 
    - '(v.n) n'

'''
def euclidean_projection(v, n):
    return as_tensor((v[beta] * n[beta]) * n[alpha], (alpha))


# vector living in the three-dimensional Euclidean space, which is orthogonal to the circle of radius r centered at c_r. N3d_c_r[k] = \vec{N}_{\gamma k}_notes
def N3d_c_r(mesh, c_r):
    x = ufl.SpatialCoordinate(mesh)
    norm = sqrt((x[0] - c_r[0]) ** 2 + (x[1] - c_r[1]) ** 2)
    return as_tensor([(x[0] - c_r[0]) / norm, (x[1] - c_r[1]) / norm, 0.0])


# Nt_c_r[i] = N_{t \gamma}^i_notes
def Nt_c_r(mesh, c_r, omega, nu=None):
    return as_tensor(g_c(omega, nu)[i, j] * N3d_c_r(mesh, c_r)[k] * e(omega, nu)[j, k], (i))


# n_c_r[i] = n_\gamma^i_notes
def n_c_r(mesh, c_r, omega, nu=None):
    return normalize(Nt_c_r(mesh, c_r, omega, nu), omega, nu)

def f_to_v(f, omega, nu=None):
    return as_tensor(g_c(omega, nu)[i, j] * f[j], (i))


def v_to_f(v, omega, nu=None):
    return as_tensor(g(omega, nu)[i, j] * v[j], (i))


'''
this method transforms a vector in the tangent bundle of \Omega to the correspoding vector in the 3d Euclidean space in which \Omega is embedded
Input values:
- 'omega': a one-form omega_i, the gradient of z
- 'v' : the  vector v^i to be transformed
Output values:
- the vector in 3d space (a tuple of 3 coordinates)
'''


def from_tangent_to_3D_space(omega, v, nu=None):
    return as_tensor(v[i] * e(omega, nu)[i, j], (j))


'''
this method takes as input a vector in the in the 3d Euclidean space and
returns its components in the tangent bundle of \Omega 
Input values:
- 'omega': a one-form omega_i, the gradient of z
- 'V' : the vector in 3d space (a tuple of 3 coordinates)
Return values:
- the tangential part V_t^i
'''

def from_3D_to_tangent(omega, V, nu=None):
    return as_tensor(g_c(omega, nu)[i, j] * V[alpha] * e(omega, nu)[j, alpha], (i))



'''
this method takes as input a vector in the in the 3d Euclidean space and
returns its component normal ot \Omega
Input values:
- 'omega': a one-form omega_i, the gradient of z
- 'V' : the vector in 3d space (a tuple of 3 coordinates)
Return values:
- the normal part V_n
'''

def from_3D_to_normal(omega, V, nu=None):
    return (V[alpha] * normal(omega, nu)[alpha])


'''
this method takes as input a vector in the in the 3d Euclidean space and returns its decomposition in components in the tangent bundle of \Omega and in the component normal ot \Omega
Input values:
- 'omega': a one-form omega_i, the gradient of z
- 'V' : the vector in 3d space (a tuple of 3 coordinates)
Return values:
- two objects: the tangential part V_t^i and the normal part V_n
'''


def from_3D_to_tangent_normal(omega, V, nu=None):
    return from_3D_to_tangent(omega, V, nu), from_3D_to_normal(omega, V, nu)


'''
this method transforms the  components tangential to \Omega and normal to \Omega of a vector, 
to the corresponding vector in the 3d Euclidean space in which \Omega is embedded
Input values:
- 'omega': a one-form omega_i, the gradient of z
- 'v_t' : the tangential component  vector v_t^i 
- 'v_n': the normal component  
Return values:
- the vector in 3d space (a tuple of 3 coordinates)
'''


def from_tangent_normal_to_3D_space(omega, v_t, v_n, nu=None):
    return from_tangent_to_3D_space(omega, v_t, nu) + v_n * normal(omega, nu)


'''
return the shape of a scalar, vector or tensor t
Input values: 
- 't': the scalar, vector or tensor
Return values:
- the shape: [1] for a scalar, [number_of_components] for a vector with 'number_of_components' components', [3,3] for a 3x3 tensor, etc... 
'''


def shape(t):
    shape = t.function_space().ufl_element().value_shape()
    return [1] if shape == () else list(shape)

'''
return a vector normalized according to a metric
Input values: 
    - 'v': the vector in the tangent bundle of the manifold, v[i] = v^i
    - 'omega': the field which serves as argument for the metric, e.g., the one-form omega_i, the gradient of z, or the angle psi
    - 'nu': the function specifying the gauge, defined, for example, by e_1^alpha e_1^alpha = nu^2 for the arc-length gauge
Return values: 
    - v^k/sqrt(g_{ij} v^i v^j )
'''
def normalize(v, omega, nu=None):
    return as_tensor(v[k] / sqrt(g(omega, nu)[i, j] * v[i] * v[j]), (k))
