'''
This code reads the ball mesh generated by ~/shared/generate_mesh/3d/ball/generate_mesh.py
and creates a submesh of it, i.e., a sphere mesh given by the boundary of the ball

Run with
    clear; clear; python3 generate_mesh.py [path where to find the mesh]
Example:
    clear; clear; INPUT_MESH_PATH="/home/fenics/shared/generate_mesh/3d/ball/solution"; SOLUTION_PATH="/home/fenics/shared/generate_mesh/3d/submesh_ball/solution"; rm -rf $SOLUTION_PATH; mkdir $SOLUTION_PATH; python3 generate_mesh.py $INPUT_MESH_PATH $SOLUTION_PATH
'''

import colorama as col
from fenics import *
import numpy as np
import sys

# add the path where to find the shared modules
module_path = '/home/fenics/shared/modules'
sys.path.append(module_path)

import calculus as cal
import differential_geometry.manifold.geometry as geo
import input_output as io
import mesh.load as lmsh
import mesh.utils as msh
import runtime_arguments as rarg

# radius of the smallest cell in the mesh
r_mesh = lmsh.mesh.hmin()

parameters = io.read_parameters_from_csv_file(rarg.args.input_directory + "/mesh_metadata.csv")


# read the mesh of the ball
ball_mesh = Mesh()
xdmf = XDMFFile(ball_mesh.mpi_comm(), rarg.args.input_directory + "/tetra_mesh.xdmf")
xdmf.read(ball_mesh)

# extract the boundary of the ball (spere) and write it in a new mesh `sphere`
dim = 3
bdim = dim - 1
sphere_mesh = BoundaryMesh(ball_mesh, "exterior")
print("Dimension of boundary_mesh = ", sphere_mesh.geometry().dim())

# read the tetrahedra
mvc = MeshValueCollection("size_t", sphere_mesh, sphere_mesh.topology().dim())
cf = cpp.mesh.MeshFunctionSizet(sphere_mesh, mvc)

dx = Measure("dx", domain=sphere_mesh, subdomain_data=cf)

# CHANGE PARAMETERS HERE
c_test = [0.3, 0.76, 1.23]
r_test = 0.345
# CHANGE PARAMETERS HERE

Q = FunctionSpace(sphere_mesh, 'P', 1)


# function_test_integrals_fenics is a function of two variables, that will be used to test whether the boundary elements ds_circle, ds_inflow, ds_outflow, .. are defined correclty . This will be done by computing an integral of f_test_ds over these boundary terms and comparing with the exact result
def function_test_integrals(x):
    return (np.cos(geo.np.linalg.norm(np.subtract(x, c_test)) - r_test) ** 2.0)
    # return 1


# function_test_integrals_fenics is the same as function_test_integrals, but in fenics format
function_test_integrals_fenics = Function(Q)


# analytical expression for a  scalar function used to test the ds
class FunctionTestIntegrals(UserExpression):
    def eval(self, values, x):
        values[0] = function_test_integrals(x)

    def value_shape(self):
        return (1,)


function_test_integrals_fenics.interpolate(FunctionTestIntegrals(element=Q.ufl_element()))

test_mesh_integral_errors = []

integral_exact_ds = cal.surface_integral_sphere(function_test_integrals, parameters["r"], parameters["c_r"])

# print out the integrals on the surface elements and compare them with the exact values to double check that the elements are tagged correctly
test_mesh_integral_errors.append(msh.test_mesh_integral(integral_exact_ds, function_test_integrals_fenics, dx, '\int_sphere f ds'))

print(f'Maximum relative error of mesh integrals = {col.Fore.RED}{max(test_mesh_integral_errors):.{io.number_of_decimals}e}{col.Fore.RESET}')
