'''
This code reads the box mesh generated by ~/shared/generate_mesh/3d/box/generate_mesh.py
and creates a sub_mesh of it, i.e., a sphere mesh given by the boundary of the box

Run with
    clear; clear; python3 generate_mesh.py [path where to find the box mesh] [path where to store the submesh]
Example:
    clear; clear; INPUT_MESH_PATH="/home/fenics/shared/generate_mesh/3d/box/solution"; SOLUTION_PATH="/home/fenics/shared/generate_mesh/3d/submesh_box/solution"; rm -rf $SOLUTION_PATH; mkdir $SOLUTION_PATH; python3 generate_mesh.py $INPUT_MESH_PATH $SOLUTION_PATH
'''


import colorama as col
from fenics import *
import meshio
import numpy as np
import sys

#add the path where to find the shared modules
module_path = '/home/fenics/shared/modules'
sys.path.append(module_path)

import calculus as cal
import differential_geometry.manifold.geometry as geo
import input_output as io
import mesh.load as lmsh
import mesh.utils as msh
import runtime_arguments as rarg

output_directory = io.add_trailing_slash(rarg.args.output_directory)


# radius of the smallest cell in the mesh
r_mesh = lmsh.mesh.hmin()

parameters = io.read_parameters_from_csv_file(rarg.args.input_directory + "/mesh_metadata.csv")


#read the mesh of the cube
box_mesh = Mesh()
xdmf = XDMFFile(box_mesh.mpi_comm(), (rarg.args.input_directory) + "/tetra_mesh.xdmf")
xdmf.read(box_mesh)



#extract the mesh corresponding to the side of the cube with y = 0 and store it in mesh2D
with XDMFFile(output_directory + "cube_mesh.xdmf") as xdmf:
    xdmf.write(box_mesh)

mesh_dimension=3
boundary_mesh_dimension = mesh_dimension - 1
cube_mesh = BoundaryMesh(box_mesh, "exterior")
print("Dimension of boundary_mesh = ", box_mesh.geometry().dim())

mapping = cube_mesh.entity_map(boundary_mesh_dimension)
part_of_cube_side = MeshFunction("size_t", cube_mesh, boundary_mesh_dimension)
#run over all cells of boundary_mesh and write `1` in part_of_cube_side for the cells which have the y component of the facet normal equal to -1 : in this way, one is selecting the cells which belong to the xz side of the box with y = 0
for cell in cells(cube_mesh):
    curr_facet_normal = Facet(box_mesh, mapping[cell.index()]).normal()
    if near(curr_facet_normal.y(), -1.0):  # On cube_side boundary
        part_of_cube_side[cell] = 1

cube_side_boundary = SubMesh(cube_mesh, part_of_cube_side, 1)
#File('cube_side_boundary.pvd') << cube_side_boundary
with XDMFFile(output_directory + "cube_side_to_prune_mesh.xdmf") as xdmf:
    xdmf.write(cube_side_boundary)



#remove the y component of the points in the cube size, transforming it from a 3d to a 2d mesh
cube_side_to_prune_mesh = meshio.read(output_directory + "cube_side_to_prune_mesh.xdmf")

cells = cube_side_to_prune_mesh.get_cells_type("triangle")
points = np.delete(cube_side_to_prune_mesh.points, 1, axis=1)
out_mesh = meshio.Mesh(points=points, cells={"triangle": cells})
meshio.write(output_directory + "cube_size_mesh.xdmf", out_mesh)

#the resulting 2d mesh is written into mesh2D
cube_size_mesh = Mesh()
with XDMFFile(output_directory + "cube_size_mesh.xdmf") as xdmf:
    xdmf.read(cube_size_mesh)
print("Dimension of cube_size_mesh = ", cube_size_mesh.geometry().dim())




#test mesh2D by integrating a function over it
# read the triangles
mvc = MeshValueCollection("size_t", cube_size_mesh, cube_size_mesh.topology().dim())
cf = cpp.mesh.MeshFunctionSizet(cube_size_mesh, mvc)

dv_custom = Measure("dx", domain=cube_size_mesh, subdomain_data=cf)    # Line measure

# CHANGE PARAMETERS HERE
c_test = [0.3, 0.76]
r_test = 0.345
# CHANGE PARAMETERS HERE

Q = FunctionSpace(cube_size_mesh, 'P', 1)


# function_test_integrals_fenics is a function of two variables, that will be used to test whether the boundary elements ds_circle, ds_inflow, ds_outflow, .. are defined correclty . This will be done by computing an integral of f_test_ds over these boundary terms and comparing with the exact result
def function_test_integrals(x):
    return (np.cos(geo.np.linalg.norm(np.subtract(x, c_test)) - r_test) ** 2.0)
    # return 1


# function_test_integrals_fenics is the same as function_test_integrals, but in fenics format
function_test_integrals_fenics = Function(Q)


# analytical expression for a  scalar function used to test the ds
class FunctionTestIntegrals(UserExpression):
    def eval(self, values, x):
        values[0] = function_test_integrals(x)

    def value_shape(self):
        return (1,)

function_test_integrals_fenics.interpolate(FunctionTestIntegrals(element=Q.ufl_element()))


test_mesh_integral_errors = []

integral_exact_ds = cal.surface_integral_rectangle(function_test_integrals, [0,0],[parameters["L"][0],parameters["L"][2]])

# print out the integrals on the surface elements and compare them with the exact values to double check that the elements are tagged correctly
test_mesh_integral_errors.append(msh.test_mesh_integral(integral_exact_ds, function_test_integrals_fenics, dv_custom, '\int_box_side f ds'))

print(f'Maximum relative error of mesh integrals = {col.Fore.RED}{max(test_mesh_integral_errors):.{io.number_of_decimals}e}{col.Fore.RESET}')
